# Generated by Django 3.2.9 on 2021-12-02 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('owner', 'book')},
        ),
    ]
