# Generated by Django 3.2.9 on 2021-12-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='title',
        ),
    ]
