# Generated by Django 3.2.9 on 2021-12-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_booktype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(),
        ),
    ]
