# Generated by Django 3.2.9 on 2021-12-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktype',
            name='thumbnail',
        ),
    ]
