# Generated by Django 3.2.9 on 2021-12-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_booktype_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('id',), 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
