# Generated by Django 3.2.9 on 2022-02-19 12:43

from django.db import migrations, models
import main.apps.book.models.book


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=main.apps.book.models.book.upload_book_cover),
        ),
    ]
