# Generated by Django 3.2.9 on 2022-02-25 09:34

from django.db import migrations, models
import main.apps.book.models.content


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.FileField(upload_to=main.apps.book.models.content.upload_book_cover),
        ),
    ]
