# Generated by Django 3.2.9 on 2022-03-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_content_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='booktype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='view',
            name='is_deleted',
        ),
    ]
