# Generated by Django 3.2.9 on 2022-08-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20220713_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='book_type',
            field=models.CharField(choices=[('online', 'online'), ('paper', 'paper'), ('audio', 'audio')], max_length=10),
        ),
    ]
