# Generated by Django 3.2.9 on 2022-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
