# Generated by Django 3.2.9 on 2022-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISNB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
