# Generated by Django 3.2.9 on 2022-09-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_book_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_created',
        ),
    ]
