# Generated by Django 3.2.9 on 2022-09-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_auto_20220916_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISNB',
            new_name='isbn',
        ),
    ]
