# Generated by Django 3.2.9 on 2022-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_rename_isnb_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='point',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3),
        ),
    ]
