# Generated by Django 3.2.9 on 2022-09-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_review_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
