# Generated by Django 3.2.9 on 2022-10-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_book_short_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_page',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover',
            field=models.CharField(choices=[('Yumshoq', 'Yumshoq'), ('Qattiq', 'Qattiq')], max_length=30, null=True),
        ),
    ]
