# Generated by Django 3.2.9 on 2022-10-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20221017_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hardcover_en',
            field=models.CharField(choices=[('Yumshoq', 'Yumshoq'), ('Qattiq', 'Qattiq')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='hardcover_ru',
            field=models.CharField(choices=[('Yumshoq', 'Yumshoq'), ('Qattiq', 'Qattiq')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='hardcover_uz',
            field=models.CharField(choices=[('Yumshoq', 'Yumshoq'), ('Qattiq', 'Qattiq')], max_length=30, null=True),
        ),
    ]
