# Generated by Django 3.2.9 on 2022-10-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0026_auto_20221017_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='hardcover',
        ),
    ]
