# Generated by Django 3.2.9 on 2022-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_auto_20221029_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='hardcover',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
