# Generated by Django 3.2.9 on 2022-10-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_auto_20221029_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='hardcover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover_ru',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='hardcover_uz',
            field=models.BooleanField(default=False),
        ),
    ]
