# Generated by Django 3.2.9 on 2022-10-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0029_auto_20221029_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='hardcover',
            new_name='hard_cover',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='hardcover_en',
            new_name='hard_cover_en',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='hardcover_ru',
            new_name='hard_cover_ru',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='hardcover_uz',
            new_name='hard_cover_uz',
        ),
    ]
