# Generated by Django 3.2.9 on 2022-03-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20211212_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_deleted',
        ),
    ]
