# Generated by Django 3.2.9 on 2022-10-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='token_for_register',
            field=models.TextField(blank=True, null=True),
        ),
    ]
