# Generated by Django 3.2.9 on 2022-10-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscription_token_for_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.CharField(choices=[(1, 'True'), (0, 'False')], default=0, max_length=255),
        ),
    ]
