# Generated by Django 3.2.9 on 2022-10-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_remove_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
