# Generated by Django 3.2.9 on 2022-10-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_subscription_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionTransaction',
        ),
    ]
