# Generated by Django 3.2.9 on 2021-12-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_balance_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='deposit',
            new_name='amount',
        ),
    ]
