# Generated by Django 3.2.9 on 2021-12-06 12:47

from django.db import migrations, models
import main.apps.account.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to=main.apps.account.models.user.upload_profile_images),
        ),
    ]
