# Generated by Django 3.2.9 on 2021-12-14 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_content_options'),
        ('account', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('online', 'online'), ('audio', 'audio')], max_length=20)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_books', to='book.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book',
                'verbose_name_plural': 'User Books',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
            ],
            options={
                'verbose_name': 'Audio Book',
                'verbose_name_plural': 'Audio Books',
                'ordering': ('-id',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userbook',),
        ),
        migrations.CreateModel(
            name='OnlineBook',
            fields=[
            ],
            options={
                'verbose_name': 'Online Book',
                'verbose_name_plural': 'Online Books',
                'ordering': ('-id',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userbook',),
        ),
    ]
