# Generated by Django 3.2.9 on 2022-01-30 16:41

from django.db import migrations, models
import main.apps.account.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_audiobook_onlinebook_userbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=main.apps.account.models.user.upload_profile_images),
        ),
    ]
