# Generated by Django 3.2.9 on 2022-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='state',
            field=models.CharField(choices=[('online', 'online'), ('audio', 'audio')], default='permanent', max_length=15),
            preserve_default=False,
        ),
    ]
