# Generated by Django 3.2.9 on 2022-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='state',
            field=models.CharField(choices=[('permanent', 'permanent'), ('temporary', 'temporary')], max_length=15),
        ),
    ]
