# Generated by Django 3.2.9 on 2022-03-09 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_userbook_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
