# Generated by Django 3.2.9 on 2022-03-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_identifier',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
