# Generated by Django 3.2.9 on 2022-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20220801_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activating_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
