# Generated by Django 3.2.9 on 2022-08-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
