# Generated by Django 3.2.9 on 2022-10-29 17:45

from django.db import migrations, models
import main.apps.account.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20221019_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=main.apps.account.models.user.upload_profile_images),
        ),
    ]
