# Generated by Django 3.2.9 on 2022-10-18 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.timedelta(seconds=60), null=True),
        ),
    ]
