# Generated by Django 3.2.9 on 2022-10-18 21:13

from django.db import migrations, models
import main.apps.account.utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_user_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expiration_date',
            new_name='expiration_time_register',
        ),
        migrations.AddField(
            model_name='user',
            name='expiration_time_reset',
            field=models.CharField(blank=True, default=main.apps.account.utils.user_expire_time, max_length=100, null=True),
        ),
    ]
