# Generated by Django 3.2.9 on 2022-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20221019_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_time_reset',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
