version: '3'

volumes:
  static_volume:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: book_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:cached
      - static_volume:/home/app/web/main/static
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: book_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
      - local_postgres_data_backups:/backups:cached
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: book_nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/main/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django