# Generated by Django 3.2.9 on 2022-03-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], default='payme', max_length=10),
            preserve_default=False,
        ),
    ]
