# Generated by Django 3.2.9 on 2022-03-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20220310_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_type',
            new_name='transaction_type',
        ),
    ]
