# Generated by Django 3.2.9 on 2022-03-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_payment_type_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='new', max_length=10),
        ),
    ]
