# Generated by Django 3.2.9 on 2022-09-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_remove_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], default=True, max_length=10),
            preserve_default=False,
        ),
    ]
