# Generated by Django 3.2.9 on 2022-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_external_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='new', max_length=10),
        ),
    ]
