# Generated by Django 3.2.9 on 2022-10-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20220928_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchatTransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('perform_time', models.IntegerField(default=0, null=True)),
                ('cancel_time', models.IntegerField(default=0, null=True)),
                ('state', models.IntegerField(default=1, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at_ms', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
