# Generated by Django 3.2.9 on 2022-10-04 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_merchattransactionsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchatTransactionsModel',
        ),
    ]
