# Generated by Django 3.2.9 on 2022-10-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0025_book_short_description_en'),
        ('transaction', '0014_delete_merchattransactionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_types', to='book.booktype'),
        ),
    ]
