# Generated by Django 3.2.9 on 2021-12-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='aaaa', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
