# Generated by Django 3.2.9 on 2021-12-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_booktype_price'),
        ('order', '0002_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='book.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='book_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='book.booktype'),
        ),
    ]
