# Generated by Django 3.2.9 on 2022-03-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220219_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
    ]
