# Generated by Django 3.2.9 on 2021-12-06 12:54

from django.db import migrations, models
import main.apps.category.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20211204_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(upload_to=main.apps.category.models.upload_category_images),
        ),
    ]
