# Generated by Django 3.2.9 on 2021-12-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_categorytype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytype',
            options={'ordering': ('id',), 'verbose_name': 'Category Type', 'verbose_name_plural': 'Category Types'},
        ),
    ]
