# Generated by Django 3.2.9 on 2022-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20220323_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
