# Generated by Django 3.2.9 on 2022-10-29 17:45

from django.db import migrations, models
import main.apps.category.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_category_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=main.apps.category.models.upload_category_images),
        ),
    ]
